-- 023: Rekonstruované DDL tabulek, které v prod existují, ale neměly žádný
-- SQL v repu (drift nalezený při baseline auditu 2026-08-03, viz
-- docs/db/BASELINE-2026-08-03.md).
--
-- NEAPLIKOVAT na prod — tabulky tam už existují. Účel: parita pro staging/dev
-- bootstrap a úplnost repa. Rekonstruováno z information_schema (sloupce,
-- defaulty); FK vazby doplněny podle zjevné sémantiky. Autoritativní zdroj
-- pravdy je prod schéma.

-- Jasné zprávy (news engine v1) ------------------------------------------------

create table if not exists public.news_editions (
  id uuid primary key default gen_random_uuid(),
  edition_type text not null,
  slug text,
  title text not null,
  subtitle text,
  summary text,
  status text not null default 'published',
  generated_at timestamptz not null default now(),
  published_at timestamptz,
  source_run_id text,
  txt_export text,
  json_export jsonb,
  created_by text not null default 'auto',
  generation_model text,
  generation_prompt_version text,
  metadata jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.news_items (
  id uuid primary key default gen_random_uuid(),
  edition_id uuid not null references public.news_editions(id) on delete cascade,
  category text not null,
  rank integer not null,
  slug text,
  headline text not null,
  short_headline text,
  lead text,
  body text not null,
  voiceover_text text,
  why_it_matters text,
  what_to_watch text,
  urgency integer default 0,
  importance integer default 0,
  confidence_score numeric,
  source_count integer default 0,
  status text not null default 'published',
  risk_flags jsonb,
  metadata jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.news_sources (
  id uuid primary key default gen_random_uuid(),
  news_item_id uuid not null references public.news_items(id) on delete cascade,
  source_title text,
  source_name text,
  source_url text,
  published_at timestamptz,
  retrieved_at timestamptz default now(),
  language text,
  source_type text,
  relevance_score numeric,
  credibility_note text,
  quote_or_excerpt text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.news_runs (
  id uuid primary key default gen_random_uuid(),
  run_type text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running',
  error_message text,
  collected_count integer default 0,
  candidate_count integer default 0,
  generated_item_count integer default 0,
  edition_id uuid references public.news_editions(id),
  metadata jsonb,
  created_at timestamptz not null default now()
);

-- Context layer (engine claims) ------------------------------------------------

create table if not exists public.contexts (
  id bigint generated by default as identity primary key,
  engine_claim_id integer not null,
  video_id text not null,
  video_title text,
  channel_name text,
  claim text not null,
  claim_type text,
  risk_score integer,
  tier text,
  context_level text,
  tldr text,
  core text,
  evidence text,
  conflict text,
  interpretation text,
  epistemic_status text,
  sources jsonb default '[]'::jsonb,
  engine_version text default '2.1',
  created_at timestamptz not null default now()
);

-- Návrhy kanálů od diváků ------------------------------------------------------

create table if not exists public.channel_suggestions (
  id uuid primary key default gen_random_uuid(),
  channel_name text not null,
  channel_url text not null,
  reason text not null,
  user_id uuid,
  created_at timestamptz not null default now()
);

-- Vyhledávání (připravená infrastruktura, zatím 0 řádků; vyžaduje pgvector) ---

create table if not exists public.verox_search_documents (
  id uuid primary key default gen_random_uuid(),
  content_type text not null,
  source_table text not null,
  source_id text not null,
  source_url text not null,
  title text not null,
  excerpt text,
  body_text text not null default '',
  source_label text,
  thumbnail_url text,
  published_at timestamptz,
  importance_score integer not null default 50,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector,
  search_vector tsvector,
  indexed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
