truncate table sources;

insert into sources (
  source_name,
  platform,
  channel_url,
  priority,
  category,
  country,
  language,
  active,
  playlist_role,
  notes
) values
  ('ABJ TV', 'youtube', 'https://www.youtube.com/@AbyByloJasno', 'A', 'komentář', 'CZ', 'cs', true, 'main', 'hlavní kanál'),
  ('XTV', 'youtube', 'https://www.youtube.com/@XTV', 'A', 'rozhovor', 'CZ', 'cs', true, 'main', null),
  ('Xaver Live', 'youtube', 'https://www.youtube.com/@XaverLive', 'A', 'komentář', 'CZ', 'cs', true, 'main', null),
  ('Rádio Universum', 'youtube', 'https://www.youtube.com/@radiouniversumcz', 'A', 'rozhovor', 'CZ', 'cs', true, 'main', 'Svobodné universum'),
  ('Protiproud', 'youtube', 'https://www.youtube.com/@ProtiproudTV', 'A', 'alternativní', 'CZ', 'cs', true, 'main', 'Petr Hájek'),
  ('Inovace Republiky', 'youtube', 'https://www.youtube.com/@InovaceRepubliky', 'A', 'rozhovor', 'CZ', 'cs', true, 'main', 'Robin Čumpelík'),
  ('Svědomí národa', 'youtube', 'https://www.youtube.com/@svedominaroda', 'A', 'rozhovor', 'CZ', 'cs', true, 'main', null),
  ('Na rovinu s Karlem Havlíčkem', 'youtube', 'https://www.youtube.com/@narovinuskh', 'A', 'politika', 'CZ', 'cs', true, 'main', null),
  ('Karel Havlíček', 'youtube', 'https://www.youtube.com/@KarelHavl%C3%AD%C4%8Dek-l1d', 'A', 'politika', 'CZ', 'cs', true, 'main', null),
  ('Sorry jako', 'youtube', 'https://www.youtube.com/@AndrejBabis', 'A', 'politika', 'CZ', 'cs', true, 'main', 'Andrej Babiš'),
  ('Tomio Okamura - oficiální profil', 'youtube', 'https://www.youtube.com/channel/UCe0c2rUjCHtQSf2XY7ulCQA', 'A', 'politika', 'CZ', 'cs', true, 'main', null),
  ('Jindřich Rajchl Česká republika', 'youtube', 'https://www.youtube.com/@Jind%C5%99ich_Rajchl/videos', 'A', 'politika', 'CZ', 'cs', true, 'main', null),
  ('Mimi Šrámová', 'youtube', 'https://www.youtube.com/@rozhovorysmimisramovou188', 'A', 'rozhovor', 'SK', 'sk', true, 'main', null),
  ('Robert Fico', 'youtube', 'https://www.youtube.com/@RobertFicoSmer', 'A', 'politika', 'SK', 'sk', true, 'main', null),
  ('Infovojna', 'youtube', 'https://www.youtube.com/@InfoVojna', 'A', 'alternativní', 'SK', 'sk', true, 'main', null),

  ('ParlamentkyTV', 'youtube', 'https://www.youtube.com/@parlamentkyTV', 'B', 'politika', 'CZ', 'cs', true, 'support', null),
  ('Deník TO', 'youtube', 'https://www.youtube.com/@denik_to', 'B', 'rozhovor', 'CZ', 'cs', true, 'support', null),
  ('Ondřej Prokop', 'youtube', 'https://www.youtube.com/@oprokop', 'B', 'politika', 'CZ', 'cs', true, 'support', null),
  ('Modrý jelen', 'youtube', 'https://www.youtube.com/@Modryjelen', 'B', 'komentář', 'CZ', 'cs', true, 'support', 'Petr Bohuš'),
  ('KTV Live', 'youtube', 'https://www.youtube.com/@ktvlive-zpravy', 'B', 'politika', 'CZ', 'cs', true, 'support', null),
  ('Raptor-TV', 'youtube', 'https://www.youtube.com/@RaptorTV.cz_hejobcane_zs', 'B', 'politika', 'CZ', 'cs', true, 'support', null),
  ('Radim Panenka', 'youtube', 'https://www.youtube.com/@RadimPanenka', 'B', 'rozhovor', 'CZ', 'cs', true, 'support', null),
  ('Gregor i Jan', 'youtube', 'https://www.youtube.com/@gregormatej', 'B', 'komentář', 'CZ', 'cs', true, 'support', null),
  ('Dvojí metr', 'youtube', 'https://www.youtube.com/@PatrikNacherCZ', 'B', 'politika', 'CZ', 'cs', true, 'support', 'Patrik Nacher'),
  ('Tomáš Lukavec', 'youtube', 'https://www.youtube.com/@zakonybohatstvi', 'B', 'rozhovor', 'CZ', 'cs', true, 'support', null),
  ('Markéta Šichtařová', 'youtube', 'https://www.youtube.com/@marketa.sichtarova', 'B', 'ekonomika', 'CZ', 'cs', true, 'support', null),
  ('Libor Vondráček', 'youtube', 'https://www.youtube.com/@svobodni', 'B', 'politika', 'CZ', 'cs', true, 'support', null),
  ('Angelika Bazalová', 'youtube', 'https://www.youtube.com/@emko-ab', 'B', 'rozhovor', 'CZ', 'cs', true, 'support', null),
  ('Markéta Dobiášová', 'youtube', 'https://www.youtube.com/@inFAKTAcz', 'B', 'rozhovor', 'CZ', 'cs', true, 'support', null),
  ('Incorrect CZ', 'youtube', 'https://www.youtube.com/@IncorrectCZ', 'B', 'komentář', 'CZ', 'cs', true, 'support', null),
  ('Marker', 'youtube', 'https://www.youtube.com/@PortalMarker', 'B', 'komentář', 'SK', 'sk', true, 'support', null),
  ('Ereport', 'youtube', 'https://www.youtube.com/@eReportTV', 'B', 'politika', 'SK', 'sk', true, 'support', null),
  ('Judita Laššáková', 'youtube', 'https://www.youtube.com/@JuditaLassakova', 'B', 'politika', 'SK', 'sk', true, 'support', null),
  ('Teraz Takto s AŽ', 'youtube', 'https://www.youtube.com/@TERAZTAKTOsAnkouZitnou', 'B', 'rozhovor', 'SK', 'sk', true, 'support', null),
  ('TVOTV', 'youtube', 'https://www.youtube.com/channel/UCVry0p4SnE6UpJCYVwaLqIg', 'B', 'zprávy', 'CZ', 'cs', true, 'support', null),
  ('SMER - Sociálna Demokracia', 'youtube', 'https://www.youtube.com/channel/UCdU1Hed-u-HJky_GNcPABeQ', 'B', 'politika', 'SK', 'sk', true, 'support', null),
  ('Ilona Švihlíková Official', 'youtube', 'https://www.youtube.com/@IlonaSvihl%C3%ADkovaOfficial', 'B', 'ekonomika', 'CZ', 'cs', true, 'support', null),
  ('Spolek Svatopluk', 'youtube', 'https://www.youtube.com/@SpolekSvatopluk', 'B', 'společnost', 'CZ', 'cs', true, 'support', null),
  ('O čem se mlčí', 'youtube', 'https://www.youtube.com/@O%C4%8Demseml%C4%8D%C3%AD', 'B', 'komentář', 'CZ', 'cs', true, 'support', null),
  ('Hlavné správy', 'youtube', 'https://www.youtube.com/@Hlavnespravy-lc9yc', 'B', 'zprávy', 'SK', 'sk', true, 'support', null),
  ('V.O.X. NEWS', 'youtube', 'https://www.youtube.com/@vox-news', 'B', 'zprávy', 'CZ', 'cs', true, 'support', null),
  ('Kateřina Konečná', 'youtube', 'https://www.youtube.com/@KonecnaKaterina/featured', 'B', 'politika', 'CZ', 'cs', true, 'support', null),
  ('Echo Podcasty', 'youtube', 'https://www.youtube.com/@echopodcasty', 'B', 'podcast', 'CZ', 'cs', true, 'support', null),
  ('Datarun', 'youtube', 'https://www.youtube.com/@Datarun_cz', 'B', 'analýza', 'CZ', 'cs', true, 'support', null),
  ('Tucker Carlson', 'youtube', 'https://www.youtube.com/@TuckerCarlson', 'B', 'zahraničí', 'US', 'en', true, 'support', 'chci dabing'),
  ('Jeffrey Sachs', 'youtube', 'https://www.youtube.com/@JeffreyDSachsOfficial', 'B', 'zahraničí', 'US', 'en', true, 'support', 'chci dabing'),

  ('Doktor Vajíčko', 'youtube', 'https://www.youtube.com/@doktoregg', 'C', 'komentář', 'CZ', 'cs', true, 'filler', null),

  ('Jindřich Rajchl', 'facebook', 'https://www.facebook.com/rajchl.jindrich', 'A', 'politika', 'CZ', 'cs', true, 'main', 'ignored in v0.2'),
  ('Andrej Babiš', 'facebook', 'https://www.facebook.com/AndrejBabis', 'A', 'politika', 'CZ', 'cs', true, 'main', 'ignored in v0.2'),
  ('Tomio Okamura', 'facebook', 'https://www.facebook.com/tomio.cz', 'A', 'politika', 'CZ', 'cs', true, 'main', 'ignored in v0.2');
